version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Alturos.VideoInfo.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: ZCexHQnm3kNKmvlowPsJZyZnI3FttfQvK8BcvJnvP6IoJnsUGpTZIaRcZFWM5jyM
  artifact: /.*\.nupkg/
